version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: orlix
      POSTGRES_USER: postgres
      POSTGRES_DB: orlix
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:orlix@db:5432/orlix
      JWT_SECRET: supersecretjwt
    ports:
      - '3001:3001'
    depends_on:
      - db
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - '3000:3000'
    depends_on:
      - api
volumes:
  db-data: {}
